on: ["push", "pull_request"]

name: Test Coveralls

jobs:

  build:
    name: Build
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        otp:
          - 25.1.2
        rebar3:
          - 3.20.0
        build_type:
          - RelWithDebInfo
        logging:
          - false
        arch:
          - x86_64
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - uses: erlef/setup-beam@v1
      with:
        otp-version: ${{ matrix.otp }}
        rebar3-version: ${{ matrix.rebar3 }}

    - name: Run cover
      run: |
        sudo apt-get install lcov
        make cover

    - name: Coveralls C
      uses: coverallsapp/github-action@v2
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        flag-name: run-c-lcov
        parallel: true
        service_job_id: ${{ github.run_id }}
        git-branch: ${{ github.ref_name }}
        git-commit: ${{ github.sha }}
        debug: true

    - name: Coveralls Erl
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_SHA: ${{ github.sha }}
        GITHUB_REF: ${{ github.ref_name }}
      run: |
        rebar3 as test coveralls send;
        sleep 5; # for debug printouts

    - name: Coveralls Finished
      uses: coverallsapp/github-action@v2
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        parallel-finished: true
